site_name: Syestematic Trading Toolkit
site_url: https://www.sttk.org
#copyright: Copyright &copy 2024-2024; Nils Kujath
extra:
  generator: false
nav:
  - Getting Started:
    - Quickstart Guide: index.md
#    - Installation: getting-started/installation.md
  - API Reference:
    - Library Overview: api-reference/library-overview.md
    - researchtools (Package):
      - csvinspector (Module): api-reference/researchtools/csvinspector.md
    - data (Package):
      - yfdownload (Module): api-reference/data/yfdownload.md
#  - Contribute:
#    - CI/CD Pipeline: contribute/cicd.md
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - search
  - git-revision-date-localized
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
repo_url: https://github.com/NilsKujath/sttk
repo_name: nilskujath/sttk
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets