site_name: STTK
site_url: https://www.sttk.org
copyright: Copyright &copy 2024-2024; Nils Kujath
extra:
  generator: false
nav:
  - Introduction: index.md
  - Quickstart Guide: quickstart.md
theme:
  name: material
  palette:
    scheme: slate
    primary: black